from __future__ import annotations

from pathlib import Path

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from app.core.llm_mode import LLMMode


class Variables(BaseSettings):
    model_config = SettingsConfigDict(extra="ignore")

    environment: str

    config_dir: Path | None = None

    log_dir: Path | None = None
    log_retention_days: int = 365

    llm_mode: LLMMode = LLMMode.STUB

    # Firebase service account used to verify App Check tokens. Required in every
    # mode that verifies them (see `LLMMode.verifies_app_check`) — startup aborts
    # without it rather than serving unverified callers.
    firebase_credentials_path: Path | None = None

    # Primary inference path: one GPU VM per model, each running backend/inference next
    # to its own vLLM instance. Path to a modelId -> URL map; required when
    # LLM_MODE is inference. See InferenceService.
    inference_endpoints_path: Path | None = None
    # Timeouts nest outside-in, every layer strictly wider than the one it wraps:
    #
    #   iOS client                    300  application.json -> network.timeoutIntervalForRequest
    #   INFERENCE_REQUEST_TIMEOUT     130  this backend waiting on the GPU VM
    #   VLLM_REQUEST_TIMEOUT          120  the VM waiting on its local engine
    #   RUNPOD_REQUEST_TIMEOUT        150  the fallback attempt after the VM gave up
    #
    # Two rules hold it together. An inner timeout below its outer one means the
    # caller hangs up on a generation that was still running and paid for. And
    # 130 + 150 has to stay under the client's 300, or the fallback finishes into
    # a connection nobody is listening to — a RunPod bill for nothing.
    inference_request_timeout_seconds: int = 130

    # Fallback inference path, used only when the GPU VM for the model fails.
    # Optional: without it a GPU failure surfaces to the client as an error.
    runpod_api_key: str | None = None
    # Path to the modelId -> endpoint URL map generated by scripts/runpod_sync.py.
    runpod_endpoints_path: Path | None = None
    # Fits in what is left of the client's budget after the GPU VM attempt. Cold
    # starts are not a factor: workersMin=1 in config/runpod_endpoints.json keeps
    # a worker warm.
    runpod_request_timeout_seconds: int = 150

    email_sender: str | None = None
    email_password: str | None = None
    email_smtp_host: str | None = None
    email_smtp_port: int | None = None

    @property
    def is_production(self) -> bool:
        # Doubles as the config directory name, so the value is the same string
        # `backend/main/config/production/` is named after.
        return self.environment == "production"

    @field_validator("llm_mode", mode="before")
    @classmethod
    def _normalize_llm_mode(cls, value: object) -> object:
        if isinstance(value, str):
            return value.lower()
        return value


variables = Variables()
