from __future__ import annotations

from pathlib import Path

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from app.core.llm_mode import LLMMode


class Variables(BaseSettings):
    model_config = SettingsConfigDict(extra="ignore")

    environment: str

    config_dir: Path | None = None

    log_dir: Path | None = None
    log_retention_days: int = 365

    llm_mode: LLMMode = LLMMode.STUB

    # Primary inference path: one GPU VM per model, each running backend/gpu next
    # to its own vLLM instance. Path to a modelId -> URL map; required when
    # LLM_MODE is inference. See GpuService.
    gpu_endpoints_path: Path | None = None
    gpu_request_timeout_seconds: int = 180

    # Fallback inference path, used only when the GPU VM for the model fails.
    # Optional: without it a GPU failure surfaces to the client as an error.
    runpod_api_key: str | None = None
    # Path to the modelId -> endpoint URL map generated by scripts/runpod_sync.py.
    runpod_endpoints_path: Path | None = None
    # Longer than the GPU timeout: a cold serverless worker has to boot first.
    runpod_request_timeout_seconds: int = 300

    email_sender: str | None = None
    email_password: str | None = None
    email_smtp_host: str | None = None
    email_smtp_port: int | None = None

    @field_validator("llm_mode", mode="before")
    @classmethod
    def _normalize_llm_mode(cls, value: object) -> object:
        if isinstance(value, str):
            return value.lower()
        return value


variables = Variables()
